name: Setup Elixir
description: Set up a specific version of OTP and Elixir and add the command-line tools to the PATH
author: GitHub
branding:
  color: blue
  icon: code
inputs:
  elixir-version:
    description: Version range or exact version of Elixir to use
  otp-version:
    description: Version range or exact version of OTP to use

runs:
  using: node12
  main: src/setup-elixir.js
